### ISSUE TITLE
on_delete missing

### ISSUE THREAD

**Issue by kerhuon** [oc-courses/decouvrez_django#1]
album = models.OneToOneField(Album) ==> on_delete arg is missing

**Comment by samir-ben** [comment]
Je crois que c'est à cause de la version utilisée de Django. Dans la class _Booking_, j'ai modifié la ligne où l'on retrouve la variable _album_ pour qu'elle devienne et cela fonctionne :
`album = models.OneToOneField(Album, on_delete=models.CASCADE)`

**Comment by celine-m-s** [comment]
C'est modifié. Merci !
